name: Terraform Cleanup on Deletion

on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]

env:
  TF_BUCKET: your-terraform-state-bucket-name

jobs:
  detect-deleted-projects:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Important for comparing commits

      - name: Detect deleted folders
        id: detect
        run: |
          parent_folder="producers"
          echo "Fetching deleted folders..."

          if [[ "${{ github.event_name }}" == "pull_request" ]]; then
            echo "Comparing for PR with origin/main..."
            deleted_folders=$(git diff --name-only --diff-filter=D origin/main | grep '/' | awk -F'/' '{print $2}' | sort -u | uniq)
          else 
            echo "Comparing for merge with origin/main..."
            deleted_folders=$(git diff --name-only --diff-filter=D HEAD^ HEAD | grep '/' | awk -F'/' '{print $2}' | sort -u | uniq)
          fi

          if [[ -z "$deleted_folders" ]]; then
            echo "No deleted folders found"
            echo "deleted_folders=" >> $GITHUB_ENV
          else
            echo "Deleted folders or files from folders before filtering are as below:"
            printf "%s\n" "${deleted_folders[@]}"
            
            valid_folders=()
            for folder in $deleted_folders; do
              if [ -d "$parent_folder/$folder" ]; then
                if find "$parent_folder/$folder" -type f | grep -q .; then
                  echo "Folder $folder still has files. Skipping deletion."
                  continue
                else
                  echo "Folder $folder is empty"
                fi
              else
                echo "Folder $folder is deleted and state file can be safely deleted"
                valid_folders+=("$folder")
              fi
            done 

            formatted_folders=$(printf '%s\n' "${valid_folders[@]}" | jq -R -s -c 'split("\n") | map(select(. != ""))')
            echo "Deleted folders after filtering are as below:"
            echo "$formatted_folders"
            echo "CLEAN_FOLDERS=$formatted_folders" >> $GITHUB_ENV
          fi

      - name: show all the github context
        run: |
          echo "event_name is  ${{ github.event_name }}"
          echo " ref_name is ${{ github.ref_name }}"
          echo " head_ref is ${{ github.head_ref }}"
          echo  "ref is ${{ github.ref }}

      - name: upload to artifact
        uses: actions/upload-artifact@v4
        with:
          name: github-context-artifact
          path: github-context.json

      - name: Show deleted folders (PR Preview)
        run: |
          if [[ "${{ github.event_name }}" == "pull_request" ]]; then
            echo "⚠️ The following folders will be removed and their Terraform state will be destroyed:"
            for folder in $(echo '${{ env.CLEAN_FOLDERS }}' | jq -r '.[]'); do
              echo "- $folder"
            done
          else
            echo "skipping as this is merge"
          fi
      - name: Delete state file from GCS
        run: |
          if [[ "${{ github.event_name }}" == "push" ]]; then
            echo "⚠️ The following folders will be removed and their Terraform state will be destroyed:"
            for folder in $(echo '${{ env.CLEAN_FOLDERS }}' | jq -r '.[]'); do
              echo "- $folder"
            done
          else
            echo "skipping as this is PR"
          fi
